---
permalink: reference-supported-operating-systems.html 
sidebar: sidebar 
keywords: installing, smi-s provider, verify, windows, host, operating systems 
summary: 在安装 SMI-S Provider 之前，您必须验证 Windows 主机是否正在运行受支持的操作系统。 
---
= 支持的操作系统版本
:allow-uri-read: 
:icons: font
:imagesdir: ./media/
:pp: &#43;&#43;


[role="lead"]
在安装 SMI-S Provider 之前，您必须验证 Windows 主机是否正在运行受支持的操作系统。

[cols="3*"]
|===
| 操作系统 | 支持的版本 | 所需的客户端软件 


 a| 
Windows
 a| 
* Microsoft Windows Server 2016
* Microsoft Windows Server 2019
* Microsoft Windows Server 2022
* Microsoft Windows Server 2025

 a| 
Microsoft Visual C ｛ pp ｝ 2010 运行时库会在 SMI-S Provider 安装期间自动安装。为了避免与运行时库相关的潜在问题，您必须安装 Microsoft Visual C ｛ pp ｝ 2010 可重新分配的软件包（ x86 ）。从以下位置： http://www.microsoft.com[]

|===


== SCVMM UR2.1要求

要使用NetApp SMI-S 5.2.7及更高版本管理NetApp文件服务器、需要System Center Virtual Machine Manager (SCVMM)更新汇总(UR）2.1。

如果没有此UR, SCVMM (版本2016、2019、2022或2025)将显示和 `Available Capacity`选项的值作为 `*0 GB*`NetApp文件服务器中现有文件共享的值 `Total Capacity`。

要运行 SMI-S Provider ，提供程序主机必须满足以下规格：

* 提供程序主机不能用于托管 Hyper-V 节点。
* SCVMM 不能在提供程序主机上运行。
* 提供程序主机不能运行内存密集型的其他程序。
* 提供程序主机不能运行任何其他供应商提供的 SMI-S 提供程序。


支持以下虚拟机管理程序：

* Microsoft Windows Server 2016 Hyper-V
* VMware ESX 5.0
* VMware ESX 5.1
* VMware ESX 5.5
* VMware ESX 6.0

