---
permalink: task-generate-a-self-signed-certificate-for-the-cim-server-windows.html 
sidebar: sidebar 
keywords: ssl authentication, enable, cim server, installation, self-signed certificate 
summary: 默认情况下， CIM 服务器启用 SSL 身份验证。在 SMI-S Provider 安装期间，将在 pegasus 目录中安装 CIM 服务器的自签名证书。您可以生成自己的自签名证书并使用它，而不是默认证书。 
---
= 为 CIM 服务器生成自签名证书
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
默认情况下，CIM 服务器启用 SSL 身份验证。在 SMI-S 提供程序安装过程中，会将 CIM 服务器的自签名证书安装到系统中。 `pegasus` 目录。您需要生成自己的自签名证书，而不是使用默认证书。


CAUTION: 安装 SMI-S 提供程序时，默认安装的自签名证书已过时。因此，在 System Center Virtual Machine Manager (SCVMM) 的“添加存储设备”中，与 SMI-S 提供程序的 SSL 连接失败。您需要为 CIM 服务器生成自签名证书，然后重新启动 SMI-S 提供程序服务。更多信息，请参阅 link:https://kb.netapp.com/data-mgmt/SMI-S/SMI-S_Issues/CSMIS-3["NetApp知识库文章：“CSMIS-3： NetApp SMI-S Provider 5.2.7 中的 cimom.cert 在安装时已过期。”"^]

.开始之前
* 您必须已以管理员身份登录。
* 您必须已访问 SMI-S Provider 。
* 您必须在 Windows 主机上下载并安装 OpenSSL。


.步骤
. 下载 `openssl.cnf` 文件： link:http://web.mit.edu/crypto/openssl.cnf["http://web.mit.edu/crypto/openssl.cnf"^]
. 移动 `openssl.cnf` 文件到bin目录：
+
`*%PEGASUS_HOME%\bin\openssl.cnf*`

. 设置 `OPENSSL_CONF` 的位置的环境变量 `openssl.cnf` 文件：
+
`*C:\ >set OPENSSL_CONF=%PEGASUS_HOME%\bin\openssl.cnf*`

+
此操作仅会在当前命令提示符会话期间设置环境变量。如果要永久设置环境变量、可以使用以下选项之一：

+
** 导航到*属性>环境变量*并更新*系统*下的变量。
** 使用命令提示符永久设置变量：
+
`*setx OPENSSL_CONF “%PEGASUS_HOME%\bin\openssl.cnf*`。

+
变量在打开新的命令提示符会话时设置。



. 导航到 `%PEGASUS_HOME%\bin` 目录：
+
`*C:\cd %pegasus_home%\bin*`

. 生成私钥：
+
` * openssl genrsa -out cimom.key 2048*`

. 生成证书请求：
+
` * openssl req -new -key cimom.key -out CIMOM.csr *`

. 出现提示时，输入证书请求的信息。
. 生成自签名证书：
+
` * openssl x509 -in CIMOM.csr -out CIMOM.cert -req -signkey cimom.key -days 1095*`

+
您可以提供不同的证书有效天数。

. 将 `CIMOM.key` 和 `CIMOM.cert` 文件复制到 `pegasus` 目录（ Windows ： `C ： \Program Files （ x86 ） \NetApp\SMIs\pegasus` ）。
. 重启 SMI-S 提供程序服务：
+
`smis cimserver restart`





== 结果

证书日期范围从当前日期开始，并在指定的天数内运行。
