---
permalink: task-manage-cimom-configuration-settings.html 
sidebar: sidebar 
keywords: smi-s provider, to manage, cimom configuration, enable, disable, http, https, port numbers 
summary: 您可以使用 SMI-S Provider 管理 CIMOM 配置，例如启用或禁用 HTTP 和 HTTPS 连接以及更改 HTTP 和 HTTPS 端口号。默认情况下， HTTP 连接处于启用状态，允许客户端在不使用 SSL 加密的情况下连接到 CIM 服务器。 
---
= 管理 CIMOM 配置设置
:icons: font
:imagesdir: ./media/


[role="lead"]
您可以使用 SMI-S Provider 管理 CIMOM 配置，例如启用或禁用 HTTP 和 HTTPS 连接以及更改 HTTP 和 HTTPS 端口号。默认情况下， HTTP 连接处于启用状态，允许客户端在不使用 SSL 加密的情况下连接到 CIM 服务器。



== 开始之前

* 您必须已具有管理员登录凭据。
* 您必须已以管理员身份登录到主机系统。




== 关于此任务

如果您的环境需要加密传入和传出 CIM 服务器的流量，则必须先禁用 HTTP 连接，然后验证是否已为 CIM 服务器启用 HTTPS 连接。



== 步骤

. 访问 NetApp SMI-S Provider 。
. 完成以下操作之一：
+
[cols="3*"]
|===
| Action | 命令 | 追加信息 


 a| 
启用 HTTP 连接
 a| 
` * cimconfig -s enableHttpConnection=true -p*`
 a| 
不适用



 a| 
禁用 HTTP 连接
 a| 
` * cimconfig -s enableHttpConnection=false -p*`
 a| 
不适用



 a| 
启用 HTTPS 连接
 a| 
` * cimconfig -s enableHttpsConnection=true -p*`
 a| 
不适用



 a| 
禁用 HTTPS 连接
 a| 
` * cimconfig -s enableHttpsConnection=false -p*`
 a| 
不适用



 a| 
修改 HTTP 端口号
 a| 
` * cimconfig -s httpport=_new_port_number_ -p*`
 a| 
默认情况下， HTTP 端口号为 5988 。例如，如果要将其更改为 5555 ，则应输入以下命令：

` * cimconfig -s https port=5555 -p*`



 a| 
修改 HTTPS 端口号
 a| 
` * cimconfig -s https Port=_new_port_number_ -p*`
 a| 
默认情况下， HTTP 端口号为 5989 。例如，如果要将其更改为 5556 ，则应输入以下命令：

` * cimconfig -s https Port=5556 -p*`

|===
. 重新启动 CIM 服务器：
+
` * SMIS cimserver restart*`


